### ISSUE TITLE
Footer Text alignment  

### ISSUE THREAD

**Issue by stevenanthonyrevo** [andrewjkramer/titan-community-bank#2]
Hi Andrew, 
 
Good stuff, just an idea to implement.  

I'd look into updating the alignment of the text in the footer maybe add the display property like "Flex". 

On mobile the text can sit on two lines centered across the bottom of the page. Thats usually good. 

Left aligned text usually needs an element on the right side of the page to make it feel balanced. 

Either way, I like to center my footer when no content is available the footer. 
 
```
.container.footer-container {
    display: flex;
    justify-content: center;
    flex-flow: wrap-reverse;
    gap: 5px;
}

```
![footer](https://github.com/andrewjkramer/titan-community-bank/assets/8505293/10de4008-b244-4685-9217-6f953151cc50)

**Comment by andrewjkramer** [comment]
Hi Steven,

Thank you for checking out the site, and submitting your feedback as my first ever GitHub repo "Issue" :satisfied:

Due to the minimal page content on this project, for the desktop view footer text I intentionally chose a non-symmetrical left-weighted position in line with the y-axis of the navigation logo (inspired by the footers of some high-traffic websites).

Thanks again for taking time to review the site and repo!
